### ISSUE TITLE
Not invincible

### ISSUE THREAD

**Issue by brunaks** [michelchenrich/invincible-tictactoe-ruby#1]
Very easy to win, please fix

<img width="470" alt="Screen Shot 2020-06-08 at 23 07 55" src="https://user-images.githubusercontent.com/13384032/84098431-a0458a80-a9dd-11ea-9fa2-e5a0931acce6.png">

**Comment by michelchenrich** [comment]
cannot reproduce plis send machine over mail thank

**Comment by michelchenrich** [comment]
ah ok i see

**Comment by michelchenrich** [comment]
now it is invincible
